### PR TITLE
worked on gaussian blur and contour finding to reduce the video noise

### PR DESCRIPTION
**Pull request by HimaPratyusha**
I improved the video's appearance in this commit by applying a method known as Gaussian blur. It gives the video a certain level of sensitivity. In the video, contours resemble the edges of objects. The video will appear cleaner if we can locate these edges and increase the prominence of the shapes and structures. This helps to improve the visual appeal of the video frames in particular.All of these adjustments are aimed at enhancing the visual quality of the video by eliminating any unwanted visual noise or distractions.

### CODE REVIEW

**Comment by shirish2001** [comment]
Can this process detect multiple colors?

**Comment by NandiSoham** [comment]
awesome implementation, it reduced so much of the background noise

**Comment by AbdulZahidShaik** [comment]
Will it work on the light backgrounds .

**Comment by HimaPratyusha** [comment]
Yes, the process described in the code can be adapted to detect multiple colors. The current implementation is set up to detect a specific color range, as defined by colourLower and colourUpper

**Pull request merged**
